os:
  - linux

cache:
  directories:
    - $HOME/cmake
    - $HOME/swig
    - $HOME/virgil

language:
  - php

php:
  - 5.6
  - 5.5
  
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - python-yaml
      - php5
      - php5-curl

before_install:
  - bash ./ci/install-cmake.sh
  - bash ./ci/install-swig.sh
  - bash ./ci/install-virgil.sh

before_script:
  - composer selfupdate
  - composer update

script:
  phpunit

notifications:
  email: "suhinin.dmitriy@gmail.com"
